# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 30, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 60, 67, 17))
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(320, 90, 86, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 130, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 27, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 90, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(40, 160, 86, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(320, 160, 86, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 240, 491, 271))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 190, 89, 25))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 514, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Рассчет"))
        self.label_3.setText(_translate("MainWindow", "Конечная дата"))
        self.label_4.setText(_translate("MainWindow", "Месяц"))
        self.label_5.setText(_translate("MainWindow", "Год"))
        self.label_6.setText(_translate("MainWindow", "Год"))
        self.label.setText(_translate("MainWindow", "Начальная дата"))
        self.label_2.setText(_translate("MainWindow", "Месяц"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Год"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Месяц"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Количество"))
        self.pushButton.setText(_translate("MainWindow", "Рассчет"))
        
        self.numRows = self.tableWidget.rowCount()

        
        
        self.pushButton.clicked.connect(self.on_click)

        for month in ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь']:
            self.comboBox.addItem(month)
            self.comboBox_2.addItem(month)
        
        for year in range(1900, 2030):
            self.comboBox_3.addItem(str(year))
            self.comboBox_4.addItem(str(year))
    def on_click(self):
        self.tableWidget.setRowCount(0)
        month_start = self.comboBox.currentText()
        month_end = self.comboBox_2.currentText()
        year_start = int(self.comboBox_3.currentText())
        year_end = int(self.comboBox_4.currentText())
        
        dni=[31,28,31,30,31,30,31,31,30,31,30,31]
        vdni=[31,29,31,30,31,30,31,31,30,31,30,31]
        mes = ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь']
        s = 0
        
       
        all_data = []

        for year in range(year_start, year_end):
            year_info = []
          
            
            n=0
    
    
            for i in mes:
                if i == month_start:
                    a=11-mes.index(i)
            n=11-a
            for j in mes:
                if mes.index(j)==n:
                    l=mes.index(j)

                   # print("\n".join(mes[l:12]))
                    for m in range(len(mes[l:12])):
                        year_info.append([year, mes[l:12][m]])
                        
            for k in range(n,mes.index('Декабрь')+1):
                if year_start % 4 == 0 and year_start % 100 != 0 or year_start % 400 == 0:
                    s=vdni[k]+s
                else:
                    s=dni[k]+s
                year_info[k].append(s)
            all_data.extend(year_info)
        
        
        last_year_info = []
        ###### Последний месяц
        for i in mes:
            if i == month_end:
                a=11-mes.index(i)
        n=11-a
        for j in mes:
            if mes.index(j)==n:
                l=mes.index(j)

                for m in range(len(mes[0:l+1])):
                    last_year_info.append([year_end, mes[0:l+1][m]])

        for k in range(mes.index('Январь'), n + 1):
            if year_end % 4 == 0 and year_end % 100 != 0 or year_end % 400 == 0:
                s=vdni[k]+s
            else:
                s=dni[k]+s
            last_year_info[k].append(s)
        all_data.extend(last_year_info)
      
        all_data.reverse()
      
        for info in all_data:
             self.tableWidget.insertRow(self.numRows) 
             self.tableWidget.setItem(self.numRows, 0, QtWidgets.QTableWidgetItem(str(info[0])))
             self.tableWidget.setItem(self.numRows, 1, QtWidgets.QTableWidgetItem(info[1]))
             self.tableWidget.setItem(self.numRows, 2, QtWidgets.QTableWidgetItem(str(info[2])))


class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())
